#!/usr/bin/env python3
"""Prepare a deployable GitHub Pages directory for PolarMeter.

The output directory contains:
- static support/policy pages
- public free-cache JSON artifacts generated by polarmeter_free_cache_worker.py
- .nojekyll for predictable static file serving

This script does not push/deploy anything. It only builds a local Pages payload.
"""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

WORKSPACE = Path(__file__).resolve().parents[1]
PROJECT = WORKSPACE
TOOLS = WORKSPACE / 'tools'
DEFAULT_SITE = PROJECT / 'github-pages-site'
DEFAULT_OUTPUT = PROJECT / '_site'
PUBLIC_FILES = ['market-snapshot-latest.json', 'market-snapshot-manifest.json', 'health.json']


def copy_site(site_dir: Path, output_dir: Path) -> None:
    if output_dir.exists():
        shutil.rmtree(output_dir)
    ignore = shutil.ignore_patterns('.DS_Store', '__pycache__')
    shutil.copytree(site_dir, output_dir, ignore=ignore)
    (output_dir / '.nojekyll').write_text('', encoding='utf-8')


def read_public_files(output_dir: Path) -> dict[str, str]:
    payload = {}
    for name in PUBLIC_FILES:
        path = output_dir / name
        if path.exists():
            payload[name] = path.read_text(encoding='utf-8')
    return payload


def restore_public_files(output_dir: Path, payload: dict[str, str]) -> None:
    for name, text in payload.items():
        (output_dir / name).write_text(text, encoding='utf-8')


def public_payload_is_publishable(output_dir: Path) -> bool:
    try:
        health = json.loads((output_dir / 'health.json').read_text(encoding='utf-8'))
        snapshot = json.loads((output_dir / 'market-snapshot-latest.json').read_text(encoding='utf-8'))
    except Exception:
        return False
    data_quality = snapshot.get('dataQuality') or {}
    return (
        health.get('ok') is True
        and data_quality.get('coreCoverageRatio') == 1.0
        and data_quality.get('displayMode') != 'collecting'
        and len((snapshot.get('news') or {}).get('items') or []) > 0
    )


def summary_from_public_payload(output_dir: Path, summary: dict[str, Any], *, reused_existing: bool) -> dict[str, Any]:
    manifest = json.loads((output_dir / 'market-snapshot-manifest.json').read_text(encoding='utf-8'))
    return {
        **summary,
        'snapshotStatus': manifest.get('snapshotStatus'),
        'okSignals': manifest.get('okSignals') or [],
        'okNewsCount': manifest.get('okNewsCount') or 0,
        'usedExistingPublicSnapshot': reused_existing,
    }


def run_worker(output_dir: Path) -> dict[str, Any]:
    cmd = [
        sys.executable,
        str(TOOLS / 'polarmeter_free_cache_worker.py'),
        '--public-dir', str(output_dir),
        '--skip-fixture',
        '--json',
    ]
    result = subprocess.run(cmd, cwd=WORKSPACE, text=True, capture_output=True, check=True)
    return json.loads(result.stdout)


def assert_pages_contract(output_dir: Path, summary: dict[str, Any]) -> None:
    for name in ['index.html', 'privacy.html', 'terms.html', 'support.html', 'styles.css', '.nojekyll', *PUBLIC_FILES]:
        if not (output_dir / name).exists():
            raise AssertionError(f'GitHub Pages payload missing {name}')

    manifest = json.loads((output_dir / 'market-snapshot-manifest.json').read_text(encoding='utf-8'))
    health = json.loads((output_dir / 'health.json').read_text(encoding='utf-8'))
    snapshot = json.loads((output_dir / 'market-snapshot-latest.json').read_text(encoding='utf-8'))

    if manifest.get('paidProviderEnabled') is not False or snapshot.get('paidProviderEnabled') is not False:
        raise AssertionError('paidProviderEnabled must remain false in public artifacts')
    if manifest.get('clientDirectProviderCalls') is not False or snapshot.get('clientDirectProviderCalls') is not False:
        raise AssertionError('clientDirectProviderCalls must remain false in public artifacts')
    if health.get('ok') is not True:
        raise AssertionError('health.json must be ok for current Pages payload')
    if summary.get('snapshotStatus') not in {'ok', 'partial'}:
        raise AssertionError(f"unexpected snapshot status for pages payload: {summary.get('snapshotStatus')}")
    data_quality = snapshot.get('dataQuality') or {}
    if data_quality.get('coreCoverageRatio') != 1.0:
        raise AssertionError(f"public snapshot must keep full core coverage, got {data_quality.get('coreCoverageRatio')}")
    if data_quality.get('displayMode') == 'collecting':
        raise AssertionError('public snapshot must not publish collecting mode')
    if not isinstance(manifest.get('newsTtlMinutes'), int) or not manifest.get('newsNextRefreshAt'):
        raise AssertionError('manifest must expose news TTL and next refresh metadata')
    if manifest.get('newsRecommendedSchedule') != '30min_weekdays_60min_weekends_public_headline_cache':
        raise AssertionError('manifest news schedule metadata mismatch')


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--site', type=Path, default=DEFAULT_SITE)
    parser.add_argument('--output', type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument('--json', action='store_true')
    args = parser.parse_args()

    copy_site(args.site, args.output)
    baseline_public_files = read_public_files(args.output)
    summary = run_worker(args.output)
    if not public_payload_is_publishable(args.output) and baseline_public_files:
        restore_public_files(args.output, baseline_public_files)
        summary = summary_from_public_payload(args.output, summary, reused_existing=True)
    else:
        summary = summary_from_public_payload(args.output, summary, reused_existing=False)
    assert_pages_contract(args.output, summary)

    payload = {
        'ok': True,
        'site': str(args.site),
        'output': str(args.output),
        'snapshotStatus': summary.get('snapshotStatus'),
        'okSignals': summary.get('okSignals'),
        'okNewsCount': summary.get('okNewsCount'),
        'usedExistingPublicSnapshot': summary.get('usedExistingPublicSnapshot') is True,
        'publicUrls': {
            'snapshot': 'market-snapshot-latest.json',
            'manifest': 'market-snapshot-manifest.json',
            'health': 'health.json',
        },
    }
    if args.json:
        print(json.dumps(payload, ensure_ascii=False, indent=2))
    else:
        print(f"PolarMeter GitHub Pages payload: PASS output={args.output} snapshot={payload['snapshotStatus']} okSignals={len(payload['okSignals'] or [])}")
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
