#!/usr/bin/env python3
"""Prepare a deployable GitHub Pages directory for PolarMeter.

The output directory contains:
- static support/policy pages
- public free-cache JSON artifacts generated by polarmeter_free_cache_worker.py
- .nojekyll for predictable static file serving

This script does not push/deploy anything. It only builds a local Pages payload.
"""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

WORKSPACE = Path(__file__).resolve().parents[1]
PROJECT = WORKSPACE
TOOLS = WORKSPACE / 'tools'
DEFAULT_SITE = PROJECT / 'github-pages-site'
DEFAULT_OUTPUT = PROJECT / '_site'
PUBLIC_FILES = ['market-snapshot-latest.json', 'market-snapshot-manifest.json', 'health.json']
LAST_KNOWN_GOOD = PROJECT / 'testflight/last-known-good-snapshot.json'


def copy_site(site_dir: Path, output_dir: Path) -> None:
    if output_dir.exists():
        shutil.rmtree(output_dir)
    ignore = shutil.ignore_patterns('.DS_Store', '__pycache__')
    shutil.copytree(site_dir, output_dir, ignore=ignore)
    (output_dir / '.nojekyll').write_text('', encoding='utf-8')


def read_public_files(output_dir: Path) -> dict[str, str]:
    payload = {}
    for name in PUBLIC_FILES:
        path = output_dir / name
        if path.exists():
            payload[name] = path.read_text(encoding='utf-8')
    return payload


def restore_public_files(output_dir: Path, payload: dict[str, str]) -> None:
    for name, text in payload.items():
        (output_dir / name).write_text(text, encoding='utf-8')


def public_payload_is_publishable(output_dir: Path) -> bool:
    try:
        health = json.loads((output_dir / 'health.json').read_text(encoding='utf-8'))
        snapshot = json.loads((output_dir / 'market-snapshot-latest.json').read_text(encoding='utf-8'))
    except Exception:
        return False
    data_quality = snapshot.get('dataQuality') or {}
    core_coverage = data_quality.get('coreCoverageRatio')
    return (
        health.get('ok') is True
        and isinstance(core_coverage, (int, float))
        and core_coverage >= 0.6
        and data_quality.get('displayMode') != 'collecting'
        and len((snapshot.get('news') or {}).get('items') or []) > 0
    )


def summary_from_public_payload(output_dir: Path, summary: dict[str, Any], *, reused_existing: bool) -> dict[str, Any]:
    manifest = json.loads((output_dir / 'market-snapshot-manifest.json').read_text(encoding='utf-8'))
    return {
        **summary,
        'snapshotStatus': manifest.get('snapshotStatus'),
        'okSignals': manifest.get('okSignals') or [],
        'okNewsCount': manifest.get('okNewsCount') or 0,
        'usedExistingPublicSnapshot': reused_existing,
    }


def seed_last_known_good_from_site(site_dir: Path, output_path: Path) -> bool:
    snapshot_path = site_dir / 'market-snapshot-latest.json'
    if not snapshot_path.exists():
        return False
    try:
        snapshot = json.loads(snapshot_path.read_text(encoding='utf-8'))
    except Exception:
        return False
    signals = snapshot.get('signals')
    if not isinstance(signals, dict) or not signals:
        return False
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps({
        'updatedAt': snapshot.get('generatedAt'),
        'source': 'github-pages-site/market-snapshot-latest.json',
        'signals': signals,
    }, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    return True


def run_worker(output_dir: Path, last_known_good: Path) -> dict[str, Any]:
    with tempfile.TemporaryDirectory(prefix='polarmeter-pages-worker-') as tmp:
        tmp_path = Path(tmp)
        cmd = [
            sys.executable,
            str(TOOLS / 'polarmeter_free_cache_worker.py'),
            '--report', str(tmp_path / 'free-provider-probe-report.json'),
            '--news-report', str(tmp_path / 'news-rss-probe-report.json'),
            '--snapshot', str(tmp_path / 'free-cache-snapshot.json'),
            '--public-dir', str(output_dir),
            '--last-known-good', str(last_known_good),
            '--skip-fixture',
            '--json',
        ]
        result = subprocess.run(cmd, cwd=WORKSPACE, text=True, capture_output=True, check=True)
        return json.loads(result.stdout)


def assert_pages_contract(output_dir: Path, summary: dict[str, Any]) -> None:
    for name in ['index.html', 'privacy.html', 'terms.html', 'support.html', 'styles.css', '.nojekyll', *PUBLIC_FILES]:
        if not (output_dir / name).exists():
            raise AssertionError(f'GitHub Pages payload missing {name}')

    manifest = json.loads((output_dir / 'market-snapshot-manifest.json').read_text(encoding='utf-8'))
    health = json.loads((output_dir / 'health.json').read_text(encoding='utf-8'))
    snapshot = json.loads((output_dir / 'market-snapshot-latest.json').read_text(encoding='utf-8'))

    if manifest.get('paidProviderEnabled') is not False or snapshot.get('paidProviderEnabled') is not False:
        raise AssertionError('paidProviderEnabled must remain false in public artifacts')
    if manifest.get('clientDirectProviderCalls') is not False or snapshot.get('clientDirectProviderCalls') is not False:
        raise AssertionError('clientDirectProviderCalls must remain false in public artifacts')
    if health.get('ok') is not True:
        raise AssertionError('health.json must be ok for current Pages payload')
    if summary.get('snapshotStatus') not in {'ok', 'partial'}:
        raise AssertionError(f"unexpected snapshot status for pages payload: {summary.get('snapshotStatus')}")
    if summary.get('freshnessAudit') != 'passed':
        raise AssertionError('pages worker summary must prove data freshness audit passed')
    data_quality = snapshot.get('dataQuality') or {}
    core_coverage = data_quality.get('coreCoverageRatio')
    if not isinstance(core_coverage, (int, float)) or core_coverage < 0.6:
        raise AssertionError(f"public snapshot must keep renderable core coverage, got {core_coverage}")
    if data_quality.get('displayMode') == 'collecting':
        raise AssertionError('public snapshot must not publish collecting mode')
    if not isinstance(manifest.get('newsTtlMinutes'), int) or not manifest.get('newsNextRefreshAt'):
        raise AssertionError('manifest must expose news TTL and next refresh metadata')
    if not isinstance(manifest.get('marketDataTtlMinutes'), int) or not manifest.get('marketDataNextRefreshAt') or not manifest.get('nextRefreshAt'):
        raise AssertionError('manifest must expose market data TTL and next refresh metadata')
    if manifest.get('newsRecommendedSchedule') != '30min_weekdays_60min_weekends_public_headline_cache':
        raise AssertionError('manifest news schedule metadata mismatch')
    if manifest.get('marketDataRecommendedSchedule') != 'market_aware_30min_weekdays_60min_weekends_kr_us_open_close_confirmations':
        raise AssertionError('manifest market data schedule metadata mismatch')
    critical_refreshes = manifest.get('criticalMarketRefreshes')
    if not isinstance(critical_refreshes, list) or len(critical_refreshes) < 8:
        raise AssertionError('manifest must expose KR/US open-close critical refresh points')
    required_refresh_keys = {
        'kr_open_plus_30', 'kr_open_plus_60', 'kr_close_plus_15', 'kr_close_plus_60',
        'us_open_plus_30', 'us_open_plus_60', 'us_close_plus_15', 'us_close_plus_60',
    }
    actual_refresh_keys = {item.get('key') for item in critical_refreshes if isinstance(item, dict)}
    missing_refresh_keys = required_refresh_keys - actual_refresh_keys
    if missing_refresh_keys:
        raise AssertionError(f'manifest missing critical refresh keys: {sorted(missing_refresh_keys)}')
    refresh_policy = manifest.get('refreshPolicy') or {}
    if refresh_policy.get('version') != 'market-aware-cache-refresh-v1':
        raise AssertionError('manifest must expose market-aware refresh policy version')
    if manifest.get('dataServingMode') not in {'normal', 'limited', 'fallback'}:
        raise AssertionError('manifest must expose dataServingMode')
    if 'lastSuccessfulSnapshotAt' not in manifest:
        raise AssertionError('manifest must expose lastSuccessfulSnapshotAt')
    retired_signals = {'kodex200', 'tiger200'}
    leaked_retired = retired_signals.intersection(snapshot.get('signals') or {})
    if leaked_retired:
        raise AssertionError(f'public snapshot leaked retired domestic ETF proxy signals: {sorted(leaked_retired)}')
    for key, signal in (snapshot.get('signals') or {}).items():
        if not isinstance(signal, dict) or signal.get('valuePolicy') != 'show':
            continue
        if not isinstance(signal.get('dataAgeHours'), (int, float)):
            raise AssertionError(f'public snapshot showable signal missing dataAgeHours: {key}')
        if not isinstance(signal.get('freshnessRank'), int):
            raise AssertionError(f'public snapshot showable signal missing freshnessRank: {key}')
    for key in ['providerCallCount', 'providerFailureCount']:
        if not isinstance(manifest.get(key), int):
            raise AssertionError(f'manifest must expose integer {key}')
    if not isinstance(manifest.get('providerStatusByName'), dict):
        raise AssertionError('manifest must expose providerStatusByName')
    for key in ['estimatedMonthlyCost', 'budgetLimit', 'killSwitchStatus', 'costGuardrails']:
        if not isinstance(manifest.get(key), dict):
            raise AssertionError(f'manifest must expose {key}')
    for key in ['budgetCapConfigured', 'commercialUseChecked', 'killSwitchActive']:
        if not isinstance(manifest.get(key), bool):
            raise AssertionError(f'manifest must expose boolean {key}')
    budget_limit = manifest.get('budgetLimit') or {}
    if manifest.get('budgetCapConfigured') is not True or budget_limit.get('monthlyLimit') != 50 or budget_limit.get('warningLimit') != 20:
        raise AssertionError('manifest must expose configured beta budget cap 20/50 USD')
    cost_guardrails = manifest.get('costGuardrails') or {}
    if cost_guardrails.get('commercialUseChecked') is not False:
        raise AssertionError('commercialUseChecked must stay false until provider terms are manually verified')
    snapshot_guardrails = snapshot.get('costGuardrails') or {}
    if (snapshot_guardrails.get('killSwitchStatus') or {}).get('rapidMoveBriefingGeneration') not in {'ready', 'off_by_kill_switch'}:
        raise AssertionError('snapshot must expose rapid move briefing kill-switch status')
    for key in ['dataServingMode', 'providerCallCount', 'providerFailureCount', 'estimatedMonthlyCost', 'budgetLimit', 'killSwitchActive', 'killSwitchStatus']:
        if key not in health:
            raise AssertionError(f'health must expose {key}')
    if health.get('marketDataRecommendedSchedule') != manifest.get('marketDataRecommendedSchedule'):
        raise AssertionError('health must expose market data refresh schedule')
    if health.get('marketDataNextRefreshAt') != manifest.get('marketDataNextRefreshAt') or health.get('nextRefreshAt') != manifest.get('nextRefreshAt'):
        raise AssertionError('health must expose market data next refresh metadata')
    if len(health.get('criticalMarketRefreshes') or []) < 8:
        raise AssertionError('health must expose critical market refresh points')


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--site', type=Path, default=DEFAULT_SITE)
    parser.add_argument('--output', type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument('--json', action='store_true')
    args = parser.parse_args()

    copy_site(args.site, args.output)
    baseline_public_files = read_public_files(args.output)
    seeded_last_known_good = seed_last_known_good_from_site(args.site, LAST_KNOWN_GOOD)
    summary = run_worker(args.output, LAST_KNOWN_GOOD)
    if not public_payload_is_publishable(args.output) and baseline_public_files:
        restore_public_files(args.output, baseline_public_files)
        summary = summary_from_public_payload(args.output, summary, reused_existing=True)
    else:
        summary = summary_from_public_payload(args.output, summary, reused_existing=False)
    assert_pages_contract(args.output, summary)

    payload = {
        'ok': True,
        'site': str(args.site),
        'output': str(args.output),
        'snapshotStatus': summary.get('snapshotStatus'),
        'okSignals': summary.get('okSignals'),
        'okNewsCount': summary.get('okNewsCount'),
        'freshnessAudit': summary.get('freshnessAudit'),
        'usedExistingPublicSnapshot': summary.get('usedExistingPublicSnapshot') is True,
        'seededLastKnownGoodFromSite': seeded_last_known_good,
        'publicUrls': {
            'snapshot': 'market-snapshot-latest.json',
            'manifest': 'market-snapshot-manifest.json',
            'health': 'health.json',
        },
    }
    if args.json:
        print(json.dumps(payload, ensure_ascii=False, indent=2))
    else:
        print(
            f"PolarMeter GitHub Pages payload: PASS output={args.output} "
            f"snapshot={payload['snapshotStatus']} okSignals={len(payload['okSignals'] or [])} "
            f"okNews={payload['okNewsCount']} reusedExisting={payload['usedExistingPublicSnapshot']} "
            f"seededLastKnownGood={payload['seededLastKnownGoodFromSite']}"
        )
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
